name: gaphor
base: core22
version: '0.1'
summary: Simple modeling tool
description: |
  Gaphor is a simple modeling tool written in Python. It is free and open source software
  for creating software and system architecture and designs. It is aimed at beginning modelers.
grade: devel # must be 'stable' to release into candidate/stable channels
issues: https://github.com/gaphor/gaphor/issues
source-code: https://github.com/gaphor/gaphor
contact: https://gaphor.org/discuss/
website: https://gaphor.org/
license: Apache-2.0
confinement: strict
icon: logos/org.gaphor.Gaphor.svg
adopt-info: gaphor

slots:
  gaphor:
    interface: dbus
    bus: session
    name: org.gnome.Gaphor

apps:
  gaphor:
    extensions: [gnome]
    command: /bin/python3 gaphor
    plugs: [home, network]
    environment:
      PYTHONPATH: "$SNAP/usr/src/gaphor:$SNAP/usr/local/lib/python3.10/site-packages:$PYTHONPATH"

parts:
  gaphor:
    plugin: python
    source: .
    #source: git@github.com:gaphor/gaphor.git
    source-type: git
    source-tag: '2.20.0'
    source-depth: 1
    # override-build: poetry install
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)

    build-packages:
      - gir1.2-pango-1.0
      - gir1.2-gtk-4.0
      - libadwaita-1-dev
      - libcairo2-dev
      - libgirepository1.0-dev
      - libgtksourceview-5-dev
      - python3-gi
      - python3-pip
      - pkg-config

    override-build: |
      apt -y remove python3-poetry python3-cairo
      
      export PYTHON_INSTALL_DIR=$SNAPCRAFT_PART_INSTALL/usr/local/lib/python3.10/site-packages
      mkdir -p $PYTHON_INSTALL_DIR
      
      curl -sSL https://install.python-poetry.org | python3 -
      /root/.local/bin/poetry config virtualenvs.create false
      /root/.local/bin/poetry install --no-dev
      craftctl default

  cleanup:
    after: [ gaphor ]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
